/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#e6f4fa",
          100: "#b3ddf1",
          200: "#80c6e8",
          300: "#4dafdf",
          400: "#2a9dd8",
          500: "#1a8fc9",
          600: "#0d7ab5",
          700: "#0a6599",
          800: "#07507d",
          900: "#043b61",
        },
        accent: {
          cyan: "#00d4ff",
          teal: "#00bfa6",
          yellow: "#ffd600",
          red: "#ff4757",
          green: "#2ed573",
          orange: "#ffa502",
        },
        gray: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '"Poppins"', "sans-serif"],
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(0, 0, 0, 0.05)",
        md: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
        xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
        card: "0 4px 24px rgba(10, 101, 153, 0.1)",
      },
      spacing: {
        sidebar: "260px",
        0.75: "3px",
        1.5: "6px",
        1.75: "7px",
        2.25: "9px",
        2.5: "10px",
        3.5: "14px",
        3.25: "13px",
        4.5: "18px",
        5.5: "22px",
        6.5: "26px",
        17.5: "70px",
        37.5: "150px",
        42.5: "170px",
        47.5: "190px",
      },
      zIndex: {
        1: "1",
        50: "50",
        100: "100",
        99: "99",
        999: "999",
        1000: "1000",
        9999: "9999",
      },
      animation: {
        fadeIn: "fadeIn 0.5s ease",
        fadeInUp: "fadeInUp 0.3s ease both",
        fadeInDown: "fadeInDown 0.3s ease both",
        slideUp: "slideUp 0.5s ease both",
        slideDown: "slideDown 0.5s ease both",
        slideInRight: "slideInRight 0.4s ease",
        slideInLeft: "slideInLeft 0.5s ease both",
        fadeOut: "fadeOut 0.4s ease 3s forwards",
        glowPulse: "glowPulse 2s ease-in-out infinite",
        pageEnter: "pageEnter 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards",
        bounceIn: "bounceIn 0.5s ease both",
        spin: "spin 0.8s linear infinite",
      },
      keyframes: {
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeInUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        fadeInDown: {
          from: { opacity: "0", transform: "translateY(-20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          from: { opacity: "0", transform: "translateY(-30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        slideInRight: {
          from: { opacity: "0", transform: "translateX(60px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        slideInLeft: {
          from: { opacity: "0", transform: "translateX(-30px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        fadeOut: {
          from: { opacity: "1" },
          to: { opacity: "0", pointerEvents: "none" },
        },
        glowPulse: {
          "0%, 100%": { boxShadow: "0 0 5px rgba(0, 212, 255, 0.2)" },
          "50%": { boxShadow: "0 0 20px rgba(0, 212, 255, 0.4)" },
        },
        pageEnter: {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        bounceIn: {
          "0%": { opacity: "0", transform: "scale(0.3)" },
          "50%": { transform: "scale(1.05)" },
          "70%": { transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
    },
  },
  plugins: [],
};
